services:
  collector:
    build:
      context: .
      dockerfile: collector/Dockerfile.collector
    ports:
      - "50051:50051"
    environment:
      - GRPC_PORT=50051

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile.gateway
    ports:
      - "8080:8080"
    depends_on:
      - collector
    environment:
      - HTTP_PORT=8080
      - COLLECTOR_ADDR=collector:50051
