FROM golang:1.25 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /collector-app ./collector/cmd

FROM alpine:3.20 AS certs
RUN apk --no-cache add ca-certificates

FROM scratch

COPY --from=builder /collector-app /collector-app
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

EXPOSE 50051

ENTRYPOINT ["/collector-app"]
